# GNU Make project makefile autogenerated by Premake

ifndef config
  config=work_win64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),work_win64)
  ifeq ($(origin CC), default)
    CC = F:\dev\gcc\bin\gcc.exe
  endif
  ifeq ($(origin CXX), default)
    CXX = F:\dev\gcc\bin\g++.exe
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  RESCOMP = default
  TARGETDIR = bin_cxx
  TARGET = $(TARGETDIR)/nc_lua
  OBJDIR = bin_cxx/win64/work
  DEFINES +=
  INCLUDES += -Isrc_cxx
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -ffloat-store -g -w -std=c99 -fpermissive
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -ffloat-store -g -w -fpermissive
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../nc_cfg/bin_cxx/nc_cfg.lib
  LDDEPS += ../nc_cfg/bin_cxx/nc_cfg.lib
  ALL_LDFLAGS += $(LDFLAGS) -L../nc_cfg -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),game_win64)
  ifeq ($(origin CC), default)
    CC = F:\dev\gcc\bin\gcc.exe
  endif
  ifeq ($(origin CXX), default)
    CXX = F:\dev\gcc\bin\g++.exe
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  RESCOMP = default
  TARGETDIR = bin_cxx
  TARGET = $(TARGETDIR)/nc_lua
  OBJDIR = bin_cxx/win64/game
  DEFINES +=
  INCLUDES += -Isrc_cxx
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -w -std=c99 -fpermissive
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -w -fpermissive
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../nc_cfg/bin_cxx/nc_cfg.lib
  LDDEPS += ../nc_cfg/bin_cxx/nc_cfg.lib
  ALL_LDFLAGS += $(LDFLAGS) -L../nc_cfg -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/nc_lua_api.o \
	$(OBJDIR)/nc_lua_code.o \
	$(OBJDIR)/nc_lua_ctype.o \
	$(OBJDIR)/nc_lua_dbg.o \
	$(OBJDIR)/nc_lua_do.o \
	$(OBJDIR)/nc_lua_dump.o \
	$(OBJDIR)/nc_lua_func.o \
	$(OBJDIR)/nc_lua_gc.o \
	$(OBJDIR)/nc_lua_init.o \
	$(OBJDIR)/nc_lua_lex.o \
	$(OBJDIR)/nc_lua_mem.o \
	$(OBJDIR)/nc_lua_obj.o \
	$(OBJDIR)/nc_lua_op_codes.o \
	$(OBJDIR)/nc_lua_parser.o \
	$(OBJDIR)/nc_lua_state.o \
	$(OBJDIR)/nc_lua_str.o \
	$(OBJDIR)/nc_lua_tab.o \
	$(OBJDIR)/nc_lua_tagm.o \
	$(OBJDIR)/nc_lua_undump.o \
	$(OBJDIR)/nc_lua_utf8.o \
	$(OBJDIR)/nc_lua_vm.o \
	$(OBJDIR)/nc_lua_zbuf.o \
	$(OBJDIR)/nc_lua_lib_aux.o \
	$(OBJDIR)/nc_lua_lib_base.o \
	$(OBJDIR)/nc_lua_lib_coro.o \
	$(OBJDIR)/nc_lua_lib_dbg.o \
	$(OBJDIR)/nc_lua_lib_io.o \
	$(OBJDIR)/nc_lua_lib_load.o \
	$(OBJDIR)/nc_lua_lib_math.o \
	$(OBJDIR)/nc_lua_lib_os.o \
	$(OBJDIR)/nc_lua_lib_str.o \
	$(OBJDIR)/nc_lua_lib_tab.o \
	$(OBJDIR)/nc_lua_comp.o \
	$(OBJDIR)/nc_lua_entry.o \
	$(OBJDIR)/nc_lua_pch.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking nc_lua
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning nc_lua
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/nc_lua_api.o: src_cxx/core/nc_lua_api.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_code.o: src_cxx/core/nc_lua_code.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_ctype.o: src_cxx/core/nc_lua_ctype.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_dbg.o: src_cxx/core/nc_lua_dbg.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_do.o: src_cxx/core/nc_lua_do.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_dump.o: src_cxx/core/nc_lua_dump.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_func.o: src_cxx/core/nc_lua_func.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_gc.o: src_cxx/core/nc_lua_gc.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_init.o: src_cxx/core/nc_lua_init.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lex.o: src_cxx/core/nc_lua_lex.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_mem.o: src_cxx/core/nc_lua_mem.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_obj.o: src_cxx/core/nc_lua_obj.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_op_codes.o: src_cxx/core/nc_lua_op_codes.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_parser.o: src_cxx/core/nc_lua_parser.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_state.o: src_cxx/core/nc_lua_state.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_str.o: src_cxx/core/nc_lua_str.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_tab.o: src_cxx/core/nc_lua_tab.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_tagm.o: src_cxx/core/nc_lua_tagm.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_undump.o: src_cxx/core/nc_lua_undump.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_utf8.o: src_cxx/core/nc_lua_utf8.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_vm.o: src_cxx/core/nc_lua_vm.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_zbuf.o: src_cxx/core/nc_lua_zbuf.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_aux.o: src_cxx/lib/nc_lua_lib_aux.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_base.o: src_cxx/lib/nc_lua_lib_base.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_coro.o: src_cxx/lib/nc_lua_lib_coro.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_dbg.o: src_cxx/lib/nc_lua_lib_dbg.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_io.o: src_cxx/lib/nc_lua_lib_io.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_load.o: src_cxx/lib/nc_lua_lib_load.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_math.o: src_cxx/lib/nc_lua_lib_math.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_os.o: src_cxx/lib/nc_lua_lib_os.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_str.o: src_cxx/lib/nc_lua_lib_str.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_lib_tab.o: src_cxx/lib/nc_lua_lib_tab.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_comp.o: src_cxx/nc_lua_comp.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_entry.o: src_cxx/nc_lua_entry.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_lua_pch.o: src_cxx/nc_lua_pch.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif